#pragma once
#include <stdint.h>

// --- ZÁKLADNÁ PALETA (RGB565 Formát) ---
#define COLOR_BLACK 0x0000
#define COLOR_WHITE 0xFFFF
#define COLOR_GREEN 0x07E0
#define COLOR_BLUE 0x001F
#define COLOR_YELLOW 0xFFE0
#define COLOR_LIGHT_GRAY 0xB5B6
#define COLOR_CYAN 0x07FF
#define COLOR_GRAY 0xC618
#define COLOR_RED 0xF800
#define COLOR_ORANGE 0xFC00
#define COLOR_LIGHT_BLUE 0x05FF
#define COLOR_DARK_RED 0xA000
#define COLOR_DARK_BLUE 0x0010

// --- TÉMA: DARK MODE (Sémantické farby / Design Tokens) ---

// Spoločné pozadie
#define THEME_BG COLOR_BLACK

// Status Bar
#define STATUS_FG COLOR_WHITE
#define STATUS_BG COLOR_BLACK
#define STATUS_BORDER_FG COLOR_GRAY
#define PROGRESS_FG COLOR_CYAN
#define STATUS_WIFI_FG COLOR_WHITE
#define STATUS_BLE_FG COLOR_CYAN
#define STATUS_OFFLINE_FG COLOR_GRAY

// Boot Obrazovka
#define BOOT_TITLE_FG COLOR_CYAN
#define BOOT_TEXT_FG COLOR_WHITE
#define BOOT_OK_FG COLOR_GREEN

// Dashboard (Senzory)
#define DASH_TEMP_BORDER COLOR_ORANGE
#define DASH_TEMP_LBL COLOR_ORANGE
#define DASH_TEMP_ICON COLOR_ORANGE
#define DASH_TEMP_VAL COLOR_WHITE
#define DASH_TEMP_DEC COLOR_LIGHT_GRAY
#define DASH_TEMP_UNIT COLOR_ORANGE

#define DASH_HUM_BORDER COLOR_LIGHT_BLUE
#define DASH_HUM_LBL COLOR_LIGHT_BLUE
#define DASH_HUM_ICON COLOR_LIGHT_BLUE
#define DASH_HUM_VAL COLOR_WHITE
#define DASH_HUM_DEC COLOR_LIGHT_GRAY
#define DASH_HUM_UNIT COLOR_LIGHT_BLUE

// Počasie (OpenWeatherMap)
#define WEATHER_TITLE_FG COLOR_GREEN
#define WEATHER_DESC_FG COLOR_YELLOW
#define WEATHER_TEMP_FG COLOR_WHITE
#define WEATHER_HUM_FG COLOR_CYAN
#define WEATHER_PRESS_FG COLOR_CYAN
#define ICON_SUN_FG COLOR_YELLOW
#define ICON_RAIN_FG COLOR_CYAN
#define ICON_SNOW_FG COLOR_WHITE
#define ICON_STORM_FG COLOR_YELLOW
#define ICON_CLOUD_FG COLOR_WHITE

// Nastavenia (Systém)
#define SYS_LABEL_FG COLOR_CYAN
#define SYS_LABEL_WIFI_FG COLOR_YELLOW
#define SYS_VALUE_FG COLOR_WHITE
#define SYS_WIFI_OK_FG COLOR_GREEN
#define SYS_WIFI_ERR_FG COLOR_RED

// Grafy
#define GRAPH_TITLE_FG COLOR_YELLOW
#define GRAPH_BG COLOR_BLACK
#define GRAPH_AXIS_FG COLOR_WHITE
#define GRAPH_AXIS_VALUE_FG COLOR_CYAN
#define GRAPH_LINE_FG COLOR_RED
#define GRAPH_POINT_FG COLOR_YELLOW
#define GRAPH_LINE_OWM_FG COLOR_BLUE
#define GRAPH_POINT_OWM_FG COLOR_CYAN
#define GRAPH_MUTED_FG COLOR_GRAY
#define GRAPH_GRID_FG COLOR_LIGHT_GRAY